projects/portal-core-ui/src/lib/portal-core.module.ts, projects/portal-core-ui/src/lib/service/wms/ol-wms.service.ts, projects/portal-core-ui/src/lib/utility/layerstatus.service.ts, projects/portal-core-ui/src/lib/utility/utilities.service.ts, projects/portal-core-ui/src/public-api.ts
To work with Carsten's backend changes.
=> Aus 3521: UI side for live refresh of stackdriver layer statuses

projects/portal-core-ui/src/lib/service/cesium-map/cs-map-object.ts, projects/portal-core-ui/src/lib/service/cesium-map/cs-map.service.ts
Constructs a list of Cesium.ProviderViewModels from the entries in the env file.
=> Construct a list of Cesium basemap layers from the provided env file.

projects/portal-core-ui/src/lib/service/cesium-map/cs-map-object.ts, projects/portal-core-ui/src/lib/service/cesium-map/cs-map.service.ts, projects/portal-core-ui/src/lib/utility/utilities.service.ts
Basically in UtilitiesService, I added a method to reproject the rectangle points into EPSG:4326.
=> AUS-3547 and AUS-3551: bbox drawing support for ASTER download and catalogue search

projects/portal-core-ui/src/lib/model/data/layer.model.ts, projects/portal-core-ui/src/lib/service/cesium-map/cs-map.service.ts, projects/portal-core-ui/src/lib/service/cswrecords/layer-handler.service.ts, projects/portal-core-ui/src/lib/service/wms/cs-wms.service.ts
Adds a flag for showing split map as well as a layer attribute detailing which side of the split the layer will appear on.
=> AUS-3559-Cesium-Split-Map

projects/portal-core-ui/src/lib/model/data/statusmap.model.ts, projects/portal-core-ui/src/lib/service/cesium-map/renderstatus/render-status.service.ts
Fixed 100% percentage loaded notification not updating in parent app until mouse over.
=> AUS-3569 Layer progress bar update at 100%

projects/portal-core-ui/src/lib/model/data/statusmap.model.ts, projects/portal-core-ui/src/lib/service/cesium-map/cs-map.service.ts
Added getters to a number of StatusMap fields that are currently private but incorrectly being used in a public context.
=> AUS-3578 Expose StatusMap Fields (for AuScope-Portal-UI Active Layers Panel)

projects/portal-core-ui/src/lib/service/wms/cs-wms.service.ts, projects/portal-core-ui/src/lib/utility/utilities.service.ts
Problem layers now load in Firefox.
=> Aus 3572 firefox styled map bug

projects/portal-core-ui/src/lib/service/cesium-map/cs-map.service.ts, projects/portal-core-ui/src/lib/service/wms/query-wms.service.ts
Using tile params instead of whole view.
=> AUS-3529 Added wmsGetfeatureInfo support.

projects/portal-core-ui/src/lib/service/cesium-map/cs-map.service.ts
Adjusted map click handler to work for WWW layers and get bounding box from CSW record as opposed to onlineResource if it can't be found in the former.
=> AUS-3591 Fix CSW map clicks

projects/portal-core-ui/src/lib/service/wms/cs-wms.service.ts
Create WMS status maps before layers are loaded, and persist the unsubscribe functions for the tile loading listeners so they can be cancelled and not call the event and interfere with the progress bar when the layer is removed.
Corresponding AuScope-PortalUI pull request: https://github.com/AuScope/AuScope-Portal-UI/pull/80
=> AUS-3618 Fix layer progress issue

projects/portal-core-ui/src/lib/model/data/statusmap.model.ts, projects/portal-core-ui/src/lib/service/cesium-map/cs-map.service.ts
Adjust layer split property when changing ImagerySplitDirection, not just directly on map.
=> AUS-3601 Fix split map

projects/portal-core-ui/src/lib/service/cesium-map/cs-map.service.ts, projects/portal-core-ui/src/lib/service/cswrecords/layer-handler.service.ts
Added 2 methods to support disabling add layers:
* getSupportedOnlineResourceTypes and
* getIsMapSupportedLayer
=> AUS-3599-Add-Layers-Only-When-Can

projects/portal-core-ui/src/lib/service/wms/cs-wms.service.ts
when a WMS layer is added to the map its extent will be captured from its metadata record to tell cesium not to load tiles outside its extent
=> limited wms layers to their csw defined extent

projects/portal-core-ui/src/lib/service/cesium-map/cs-clipboard.service.ts, projects/portal-core-ui/src/lib/service/cesium-map/cs-map-object.ts, projects/portal-core-ui/src/lib/service/cesium-map/cs-map.service.ts, projects/portal-core-ui/src/lib/service/kml/cs-iris.service.ts, projects/portal-core-ui/src/lib/service/permanentlink/manage-state.service.ts, projects/portal-core-ui/src/lib/service/wcsw/ol-csw.service.ts, projects/portal-core-ui/src/lib/service/wfs/cs-wfs.service.ts, projects/portal-core-ui/src/lib/service/wms/cs-wms.service.ts, projects/portal-core-ui/src/lib/service/wms/query-wms.service.ts
IRIS layers can now be clicked. Lots of OpenLayers legacy junk removed.
=> AUS-3592 IRIS layers can now be clicked

projects/portal-core-ui/src/lib/service/cesium-map/cs-clipboard.service.ts, projects/portal-core-ui/src/lib/service/cesium-map/cs-map-object.ts, projects/portal-core-ui/src/lib/service/cesium-map/cs-map.service.ts
Remove polygon context menu click.
Better name polygons.
Can interrogate map object for polygon being drawn.
=> Aus 3621 remove polygon filter context menu

projects/portal-core-ui/src/lib/model/data/layer.model.ts, projects/portal-core-ui/src/lib/service/cswrecords/layer-handler.service.ts, projects/portal-core-ui/src/lib/service/wcs/download/download-wcs.service.ts, projects/portal-core-ui/src/lib/service/wms/cs-wms.service.ts, projects/portal-core-ui/src/lib/utility/constants.service.ts, projects/portal-core-ui/src/lib/utility/layerstatus.service.ts, projects/portal-core-ui/src/lib/utility/utilities.service.ts
Changes to support time parameters in WMS and WCS requests
=> Aus 3598 Changes to support time parameters in WMS and WCS requests

projects/portal-core-ui/src/lib/model/data/statusmap.model.ts, projects/portal-core-ui/src/lib/service/wms/cs-wms.service.ts
Fix AUS-3603: Logic corrected and generally better error communication
=> Fix AUS-3603: Logic corrected and generally better error communication

projects/portal-core-ui/src/lib/service/cesium-map/cs-map.service.ts
Re-implemented fitView to allow zooming to extent.
=> AUS-3609 Preview map click to zoom

projects/portal-core-ui/src/lib/service/cswrecords/layer-handler.service.ts
Added a check for CSW records existence when getting custom layer records.
=> AUS-3632 Catalogue and Custom load layer spinners

projects/portal-core-ui/src/lib/service/cesium-map/renderstatus/render-status.service.ts
Removed unneeded appRef.tick calls.
=> AUS-3634 Recursive Error

projects/portal-core-ui/src/lib/service/wfs/download/download-wfs.service.ts
Changed to httpPost method due to long httpParams.
=> AUS-3663 Added polygonFilter param to download.

projects/portal-core-ui/src/lib/service/wms/get-caps.service.ts
=> Add "ows:AccessConstraints" to get-caps.service.ts

projects/portal-core-ui/src/lib/utility/utilities.service.ts
Don't look for time parameter if already supplied.
=> AUS-3739 WMS Time Selection Bug

package-lock.json, package.json, projects/portal-core-ui/package.json, projects/portal-core-ui/src/lib/service/cesium-map/cs-clipboard.service.ts, projects/portal-core-ui/src/lib/service/permanentlink/manage-state.service.ts
Allow adding advanced filters and WMS time to save state.
=> AUS-3722 GRACE Filters

projects/portal-core-ui/src/lib/model/data/cswrecord.model.ts, projects/portal-core-ui/src/lib/utility/simplexml.service.ts
Added funderOrg field to CSWRecordModel.
=> AUS-3683 Funder Info

projects/portal-core-ui/src/lib/service/wms/get-caps.service.ts
Remove unnecessary parameters from custom layer service URLs keeping only the version.
=> AUS-3560 Custom layers

projects/portal-core-ui/src/lib/service/cswrecords/layer-handler.service.ts, projects/portal-core-ui/src/lib/service/permanentlink/manage-state.service.ts, yarn.lock
Loaded layers now an observable.
Also created observable for layers that need to be expanded so this can be done outside LayersPanel.
=> AUS-3808 Improved Search

package.json, projects/portal-core-ui/package.json, projects/portal-core-ui/src/lib/service/wms/get-caps.service.ts
Added a check to make sure the urlNeedProxy setting is present.
=> AUS-3844 Aster layer getCaps fix

package.json, projects/portal-core-ui/package.json, projects/portal-core-ui/src/lib/portal-core.module.ts, projects/portal-core-ui/src/lib/service/permanentlink/manage-state.service.ts, projects/portal-core-ui/src/lib/service/style/wms/sld.service.ts, projects/portal-core-ui/src/lib/service/wms/cs-wms.service.ts, projects/portal-core-ui/src/public-api.ts
Moved SLD creation to its own service and allowed retrieving of layer states to better facilitate map legends.
=> AUS-3886 Map Legends

projects/portal-core-ui/src/lib/model/data/layer.model.ts
Changed LayerModel's staticLegendUrl field to legendImg.
=> AUS-3890 Static Legends

projects/portal-core-ui/src/lib/service/cesium-map/cs-map.service.ts, projects/portal-core-ui/src/lib/utility/utilities.service.ts
Add a test for whether a layer supports opacity.
=> AUS-3888 Remove opacity slider for unsupported layers

package.json, projects/portal-core-ui/package.json, projects/portal-core-ui/src/lib/service/permanentlink/manage-state.service.ts
Remove unnecessary return that was sometimes causing time to be ignored
=> AUS-3906 States to DB

package.json, projects/portal-core-ui/package.json, projects/portal-core-ui/src/lib/model/data/layer.model.ts, projects/portal-core-ui/src/lib/model/data/mapstate.model.ts, projects/portal-core-ui/src/lib/service/cesium-map/cs-map-object.ts, projects/portal-core-ui/src/lib/service/cesium-map/cs-map.service.ts, projects/portal-core-ui/src/lib/service/permanentlink/manage-state.service.ts, projects/portal-core-ui/src/lib/service/wms/cs-wms.service.ts
Changed CsMapService's layerModelList from a Map to Array to allow for easier layer ordering.
Added method to CsMapService to allow layer reordering.
=> AUS-3917 Layer Reordering

projects/portal-core-ui/src/lib/service/kml/cs-kml.service.ts
Allow KML layers that are in the process of being added to be cancelled.
=> AUS-3893 KML layer deletion

projects/portal-core-ui/src/lib/service/cesium-map/cs-map.service.ts
Removed Natural Earth basemap due to lack of resolution.
=> AUS-3920 Remove NaturalEarthII BaseMap

package.json, projects/portal-core-ui/package.json, projects/portal-core-ui/src/lib/service/cesium-map/cs-map.service.ts
Base Map can be set by passing in the base map name.
=> AUS-3919 Persist Base Map

projects/portal-core-ui/package.json, projects/portal-core-ui/src/lib/service/wfs/download/download-wfs.service.ts
Allow omitting gsmlp:shape property from WFS download filter.
=> AUS-3837 datasetUrlSupportedLayer

package.json, projects/portal-core-ui/package.json, projects/portal-core-ui/src/lib/model/data/layer.model.ts, projects/portal-core-ui/src/lib/service/cswrecords/layer-handler.service.ts, projects/portal-core-ui/src/lib/service/kml/kml.service.ts, projects/portal-core-ui/src/lib/service/wms/cs-wms.service.ts, projects/portal-core-ui/src/lib/service/wms/get-caps.service.ts
Fixed GetCapsService issue where parameters were being dropped and calls were showing no layers in the UI.
Added attributes to LayerModel to allow custom layers to skip whitelist check.
=> AUS-3914 Custom layers proxy

projects/portal-core-ui/src/lib/utility/simplexml.service.ts
Add XML methods for extracting Intersects filters from an XML SLD_BODY.
=> AUS-3967 Polygon filter clicks

package-lock.json, package.json, projects/portal-core-ui/package.json, projects/portal-core-ui/src/lib/model/data/cswrecord.model.ts, projects/portal-core-ui/src/lib/service/cswrecords/layer-handler.service.ts
Added knownLayerIds to CSWRecordModel
=> AUS-4031 Elasticsearch CSW Search

projects/portal-core-ui/src/lib/service/cswrecords/layer-handler.service.ts, projects/portal-core-ui/src/lib/service/wms/cs-wms.service.ts
- Add missing group for custom layers to prevent future errors
- Ensure that Esri ArcGIS layer map requests are always sent as simple proxy-less GET requests
=> AUS-4142 Fix custom layers

projects/portal-core-ui/src/lib/service/wms/get-caps.service.ts
Fixed being able to read nested layers in GetCapabilities responses when adding custom layers from WMS sources.
=> AUS-4039/4216 Cusotm Layers GetCapabilities Nested Layers

projects/portal-core-ui/src/lib/model/data/layer.model.ts, projects/portal-core-ui/src/lib/service/wms/get-caps.service.ts
Add Min/MaxScaleDenominators to a GetCapabilityRecord's LayerModels (if present).
=> AUS-4049 Custom Layers Zoom Issue

projects/portal-core-ui/src/lib/service/cesium-map/cs-clipboard.service.ts
Fixed issue with polygon XML being parsed incorrectly.
=> AUS-4218 Geo-Provinces Polygons Broken

projects/portal-core-ui/src/lib/service/permanentlink/manage-state.service.ts, projects/portal-core-ui/src/lib/service/wms/legend.service.ts
Remove unused portal state calls.
=> AUS-4325 Remove Obselete Calls

projects/portal-core-ui/src/lib/service/cesium-map/cs-map.service.ts, projects/portal-core-ui/src/lib/service/wms/cs-wms.service.ts
Shifted code so all resource types zoom to initialBbox on layer load.
=> AUS-4018 CSW records initial zoom

package-lock.json, package.json, projects/portal-core-ui/src/lib/service/wcs/download/download-wcs.service.ts, projects/portal-core-ui/src/lib/service/wcs/get-coverage.service.ts, projects/portal-core-ui/src/lib/utility/utilities.service.ts, projects/portal-core-ui/src/types/epsg.d.ts, projects/portal-core-ui/tsconfig.lib.json
- Augment WCS 'DescribeCoverage' to use a proxy
- Add new function to convert Bbox coords to a different CRS
=> Aus 4371: Improve WCS proxy and coord conversion

projects/portal-core-ui/src/lib/service/style/wms/borehole-style.service.ts, projects/portal-core-ui/src/lib/service/style/wms/nvcl-borehole-style.service.ts
=> AUS-4404 Fixed name filter for allboreholes layer
